name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install debhelper build-essential devscripts -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build package
        run: |+
          TAG=${{ github.ref_name }}
          ./dch.sh $TAG
          debuild -i -uc -us -b
          cd ..
          echo "Result: $(ls *.deb)"
          sha512sum *.deb > checksums.txt
          cd ${{ github.workspace }}
          gh release delete $TAG || true
          gh release create $TAG --generate-notes ../*.deb ../checksums.txt
        env:
          GH_TOKEN: ${{ github.token }}
